### ISSUE TITLE
Configuracion MongoDB

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i004-wander-back-java#8]

**Comment by EBDev81** [comment]
Comenzando la configuración de MongoDB.

**Comment by EBDev81** [comment]
INCIDENCIA: 

Configurada la conexión a MongoDB **a falta de la uri correcta donde estará la base de datos del proyecto**. De momento dejo una provisional que da un error al levantar la aplicación pero sigue corriendo igualmente:

Linea 5 del application.properties donde está la uri: 
# MongoDB configuration (provisional uri)
spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/baeldung

Error mostrado al levantar el servicio: 
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.lambda$open$0(SocketStream.java:86) ~[mongodb-driver-core-5.0.1.jar:na]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[na:na]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:86) ~[mongodb-driver-core-5.0.1.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:201) ~[mongodb-driver-core-5.0.1.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:193) ~[mongodb-driver-core-5.0.1.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:153) ~[mongodb-driver-core-5.0.1.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:76) ~[mongodb-driver-core-5.0.1.jar:na]
	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:105) ~[mongodb-driver-core-5.0.1.jar:na]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:80) ~[mongodb-driver-core-5.0.1.jar:na]
	... 4 common frames omitted

![Image](https://github.com/user-attachments/assets/695935a6-2622-49fc-b353-1f854003f1c1)

**Comment by gonzavillalta** [comment]
Revisando con DevOps la utilización de Mongo como BD, tenemos la restricción, por el momento, de no contar con alojamiento gratuito para alojar y levantarla. Jose va a revisar si tenemos esta posibilidad

Alternativa sugerida: DinamoDB alojamiento AWS

Restricción entre Alternativas: Para adaptar la estructura sugerida en MongoDB se debe utilizar DocumentDB.

**Comment by EBDev81** [comment]
Finalmente comenzaremos trabajando con MongoDB en local, me pongo a configurar

**Comment by EBDev81** [comment]
Conexión Correcta a MongoDB EN LOCAL (es necesario instalar mongodb en los ordenadores):

La conexión a MongoDB se ha realizado sin problemas, como se observa en el log de spring:
org.mongodb.driver.cluster: Monitor thread successfully connected to server with description...

El servidor Tomcat se ha inicializado sin problemas:
Tomcat initialized with port 8080 (http)

La aplicación funciona sin problemas pero no se genera ninguna BD. He hecho solo la configuración general. En el push que he hecho en esta rama está el fichero .env con la configuración inicial sin cambiar.

Se han eliminado dependencias innecesarias del pom.xml y también se ha eliminado configuraciones innecesarias del application.properties.

Para que el proyecto siga arrancando sin problemas he cambiado anotaciones en la entity inicial

**Comment by EBDev81** [comment]
Esperando aprobación de la PR. ya está finalizado.

**Comment by EBDev81** [comment]
pr aprobada y mergeada
